version: '3'

services:
  postgres:
    image: mysql:5.7
    container_name: poker
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=poker
      - MYSQL_ROOT_PASSWORD=1234
      # TODO 유저 등록하여 사용